(function(){
  const DATA = [
    { en: 'The dog', pt: 'O cachorro' },
    { en: 'The cat', pt: 'O gato' },
    { en: 'The horse', pt: 'O cavalo' },
    { en: 'The cow', pt: 'A vaca' },
    { en: 'The pig', pt: 'O porco' },
    { en: 'The sheep', pt: 'O carneiro' },
    { en: 'The goat', pt: 'A cabra' },
    { en: 'The rabbit', pt: 'O coelho' },
    { en: 'The lion', pt: 'O leão' },
    { en: 'The tiger', pt: 'O tigre' },
    { en: 'The elephant', pt: 'O elefante' },
    { en: 'The giraffe', pt: 'A girafa' },
    { en: 'The monkey', pt: 'O macaco' },
    { en: 'The bear', pt: 'O urso' },
    { en: 'The wolf', pt: 'O lobo' },
    { en: 'The fox', pt: 'A raposa' },
    { en: 'The deer', pt: 'O cervo / veado' },
    { en: 'The bird', pt: 'O pássaro' },
    { en: 'The eagle', pt: 'A águia' },
    { en: 'The duck', pt: 'O pato' },
    { en: 'The chicken / The rooster', pt: 'O frango / O galo' },
    { en: 'The hen', pt: 'A galinha' },
    { en: 'The fish', pt: 'O peixe' },
    { en: 'The shark', pt: 'O tubarão' },
    { en: 'The whale', pt: 'A baleia' },
    { en: 'The dolphin', pt: 'O golfinho' },
    { en: 'The turtle', pt: 'A tartaruga' },
    { en: 'The snake', pt: 'A cobra' },
    { en: 'The frog', pt: 'A rã' },
    { en: 'The bee', pt: 'A abelha' },
    { en: 'The butterfly', pt: 'A borboleta' },
    { en: 'The ant', pt: 'A formiga' },
    { en: 'The spider', pt: 'A aranha' },
    { en: 'The mouse', pt: 'O rato' },
    { en: 'The rat', pt: 'A ratazana' },
  ];

  QuizCore.createGame(DATA, { title: 'Animais — Inglês → Português', rounds: 10 });
})();
