(function(){
  const DATA = [
    { en: 'The fork', pt: 'O garfo' },
    { en: 'The knife', pt: 'A faca' },
    { en: 'The spoon', pt: 'A colher' },
    { en: 'The tablespoon', pt: 'A concha / colher de sopa' },
    { en: 'The teaspoon', pt: 'A colher de café' },
    { en: 'The fish fork', pt: 'O garfo de peixe' },
    { en: 'The steak knife', pt: 'A faca de bife' },
    { en: 'The plate', pt: 'O prato' },
    { en: 'The dinner plate', pt: 'O prato raso' },
    { en: 'The soup bowl (deep plate)', pt: 'O prato fundo' },
    { en: 'The dessert plate', pt: 'O prato de sobremesa' },
    { en: 'The soup plate', pt: 'O prato de sopa' },
    { en: 'The bowl', pt: 'A tigela / caneca' },
    { en: 'The cup', pt: 'A xícara' },
    { en: 'The coffee cup', pt: 'A xícara de café' },
    { en: 'The teacup', pt: 'A xícara de chá' },
    { en: 'The glass', pt: 'O copo' },
    { en: 'The water glass', pt: 'O copo de água' },
    { en: 'The wine glass', pt: 'A taça de vinho' },
    { en: 'The champagne flute', pt: 'A taça de champanhe' },
    { en: 'The saucer', pt: 'O pires' },
    { en: 'The placemat', pt: 'O jogo americano' },
    { en: 'The napkin', pt: 'O guardanapo' },
    { en: 'The paper napkin', pt: 'O guardanapo de papel' },
    { en: 'The cloth napkin', pt: 'O guardanapo de pano' },
    { en: 'The dish towel', pt: 'O pano de prato' },
    { en: 'The tablecloth', pt: 'A toalha de mesa' },
    { en: 'The dish', pt: 'O travessa / prato' },
    { en: 'The baking dish', pt: 'A assadeira' },
    { en: 'The frying pan', pt: 'A frigideira' },
    { en: 'The pot', pt: 'A panela' },
    { en: 'The stock pot', pt: 'A panela / caldeirão' },
    { en: 'The colander', pt: 'O escorredor' },
    { en: 'The skimmer', pt: 'A escumadeira' },
    { en: 'The whisk', pt: 'O batedor / fouet' },
    { en: 'The spatula', pt: 'A espátula' },
    { en: 'The ladle', pt: 'A concha' },
    { en: 'The measuring cup', pt: 'A medida' },
    { en: 'The rolling pin', pt: 'O rolo de massa' },
    { en: 'The mixing bowl', pt: 'A tigela de mistura' },
    { en: 'The salad bowl', pt: 'A saladeira' },
    { en: 'The carafe', pt: 'A garrafa' },
    { en: 'The teapot', pt: 'O bule de chá' },
    { en: 'The coffeepot', pt: 'A cafeteira' },
    { en: 'The sugar bowl', pt: 'O açucareiro' },
    { en: 'The butter dish', pt: 'O manteigueira' },
    { en: 'Salt and pepper', pt: 'O sal e a pimenta' },
    { en: 'The salt shaker', pt: 'O saleiro' },
    { en: 'The pepper shaker', pt: 'O pimenteiro' },
  ];

  QuizCore.createGame(DATA, { title: 'Louças — Inglês → Português', rounds: 10 });
})();
