(function(){
  const DATA = [
    { en: 'The house', pt: 'A casa' },
    { en: 'The kitchen', pt: 'A cozinha' },
    { en: 'The living room', pt: 'A sala de estar' },
    { en: 'The bedroom', pt: 'O quarto' },
    { en: 'The bathroom', pt: 'O banheiro' },
    { en: 'The toilet', pt: 'O banheiro / WC' },
    { en: 'The garden', pt: 'O jardim' },
    { en: 'The garage', pt: 'A garagem' },
    { en: 'The basement', pt: 'O porão' },
    { en: 'The attic', pt: 'O sótão' },
    { en: 'The entryway', pt: 'A entrada / hall' },
    { en: 'The hallway', pt: 'O corredor' },
    { en: 'The stairs', pt: 'A escada' },
    { en: 'The balcony', pt: 'A varanda' },
    { en: 'The terrace', pt: 'O terraço' },
    { en: 'The roof', pt: 'O telhado' },
    { en: 'The wall', pt: 'A parede' },
    { en: 'The door', pt: 'A porta' },
    { en: 'The window', pt: 'A janela' },
    { en: 'The floor', pt: 'O chão' },
    { en: 'The ceiling', pt: 'O teto' },
    { en: 'The dining room', pt: 'A sala de jantar' },
    { en: 'The office', pt: 'O escritório' },
    { en: 'The bookshelf', pt: 'A biblioteca / estante' },
    { en: 'The cellar', pt: 'A adega / porão' },
    { en: 'The porch', pt: 'A varanda coberta' },
    { en: 'The patio', pt: 'O pátio' },
    { en: 'The fence', pt: 'A cerca' },
    { en: 'The gate', pt: 'O portão' },
    { en: 'The chimney', pt: 'A chaminé' },
    { en: 'The laundry room', pt: 'A lavanderia' },
    { en: 'The walk-in closet', pt: 'O closet / guarda-roupa' },
    { en: 'The workshop', pt: 'A oficina' },
    { en: 'The pantry', pt: 'A despensa' },
  ];

  QuizCore.createGame(DATA, { title: 'Partes da Casa — Inglês → Português', rounds: 10 });
})();
