(function(){
  const DATA = [
    { en: 'The head', pt: 'A cabeça' },
    { en: 'The skull', pt: 'O crânio' },
    { en: 'The brain', pt: 'O cérebro' },
    { en: 'The face', pt: 'O rosto' },
    { en: 'The eye (pl. the eyes)', pt: 'O olho (os olhos)' },
    { en: 'The eyebrow', pt: 'A sobrancelha' },
    { en: 'The eyelid', pt: 'A pálpebra' },
    { en: 'The nose', pt: 'O nariz' },
    { en: 'The cheek', pt: 'A bochecha' },
    { en: 'The mouth', pt: 'A boca' },
    { en: 'The lips', pt: 'Os lábios' },
    { en: 'The tooth', pt: 'O dente' },
    { en: 'The tongue', pt: 'A língua' },
    { en: 'The chin', pt: 'O queixo' },
    { en: 'The neck', pt: 'O pescoço' },
    { en: 'The throat', pt: 'A garganta' },
    { en: 'The shoulder', pt: 'O ombro' },
    { en: 'The shoulders', pt: 'Os ombros' },
    { en: 'The hair', pt: 'O cabelo' },
    { en: 'The forehead', pt: 'A testa' },
    { en: 'The ears', pt: 'As orelhas' },
    { en: 'The arm', pt: 'O braço' },
    { en: 'The elbow', pt: 'O cotovelo' },
    { en: 'The wrist', pt: 'O pulso' },
    { en: 'The hand', pt: 'A mão' },
    { en: 'The finger', pt: 'O dedo' },
    { en: 'The nail', pt: 'A unha' },
    { en: 'The chest', pt: 'O peito / O tórax' },
    { en: 'The heart', pt: 'O coração' },
    { en: 'The lung', pt: 'O pulmão' },
    { en: 'The stomach', pt: 'O estômago' },
    { en: 'The belly', pt: 'A barriga / O ventre' },
    { en: 'The liver', pt: 'O fígado' },
    { en: 'The intestine', pt: 'O intestino' },
    { en: 'The kidney', pt: 'O rim' },
    { en: 'The back', pt: 'As costas' },
    { en: 'The spine', pt: 'A coluna vertebral' },
    { en: 'The hip', pt: 'O quadril' },
    { en: 'The leg', pt: 'A perna' },
    { en: 'The thigh', pt: 'A coxa' },
    { en: 'The knee', pt: 'O joelho' },
    { en: 'The ankle', pt: 'O tornozelo' },
    { en: 'The foot', pt: 'O pé' },
    { en: 'The toe', pt: 'O dedo do pé' },
    { en: 'The blood', pt: 'O sangue' },
    { en: 'The bone', pt: 'O osso' },
    { en: 'The muscle', pt: 'O músculo' },
    { en: 'The skin', pt: 'A pele' },
  ];

  QuizCore.createGame(DATA, { title: 'Partes do Corpo — Inglês → Português', rounds: 10 });
})();
